version: '3.7'
services:
  insurance-calculator:
    build: .
    depends_on:
      - jaeger
    ports:
      - "8080:8080"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SAMPLER_PARAM=1
